---
title: "STAT 400 - GLM Milestone 1 Report"
author: "Ishan Agrahar, Jake Sturges, Noah Tobias, Prajwal Bhandari"
date: "2025-12-02"
output: html_document
---

## Front Matter
```{r}
# Libraries
library(tidyverse)

# Dataset
NBAGameData <- read.csv("CleanedData/NBATeamData.csv")
```

## Research Question
The goal of this logistic regression project is to predict if a team in the National Basketball Association (NBA) will make the playoffs.

## Dataset Description

NOTE: We created the cleaned dataset `NBAGameData` above based on the below raw datasets

The main raw dataset that our team chose is located at: <https://github.com/NocturneBear/NBA-Data-2010-2024/blob/main/regular_season_totals_2010_2024.csv>

It includes many teams statistics for each NBA team, however, notably missing from this dataset is whether a team made the playoffs.

This is the main response variable so this was added through data located at: <https://basketball.realgm.com/nba/playoffs/history/2010>

For the code that we created for making the cleaned dataset `NBAGameData`, please see <https://github.com/LoyalParrot/STAT_400-Final_Project/blob/main/GLMmilestone1/DatasetCreation.Rmd>.

A single observation in this dataset will be a NBA team during a given season.

## Variable Description

SEASON_YEAR - a variable describing the season in which a given team played

TEAM_NAME - describes a teams name and the city they play for

FGA - average number of field goals attempted per game

FGM - average number of field goals made per game

FG_PCT - average field goal percentage per game

FG3M -average number of 3 pointers made per game

FG3A - average number of 3 pointers attempted per game

FG3_PCT - average 3 point percentage per game

FTM - average number of free throws made per game

FTA - average number of free throws attempted per game

FTPCT - average free throw percentage per game

OREB - average number of offensive rebounds per game

DREB - average number of defensive rebounds per game

REB - average number of rebounds per game

AST - average number of assists per game

TOV - average number of turnovers per game

STL - average number of steals per game

BLK - average number of blocks per game

BLKA - average number of blocks against per game

PF - average number of personal fouls per game

PFD - average number of personal fouls drawn per game

PTS - average number of total points per game

PLUS_MINUS - average number of points scored more than opponent

WINPCT - a teams win percentage on the season

CONFERENCE - a variable describing which conference a team is in taking values "Western" or "Eastern"

### Response Variable

The response variable is `PlayoffAppearanceIndicator` which is a binary indicator variable with a value of 1 for if a team made the playoffs in a the specified season and 0 otherwise.
